apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blahbox
  name: blahbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blahbox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blahbox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c 
        - "sleep 3600"
        image: busybox
        name: busybox
        resources: {}
status: {}
