# permissions for end users to view sleepynodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sleepynode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sleepy-node-scheduler
    app.kubernetes.io/part-of: sleepy-node-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: sleepynode-viewer-role
rules:
- apiGroups:
  - batch.6740.io
  resources:
  - sleepynodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.6740.io
  resources:
  - sleepynodes/status
  verbs:
  - get
